### DISCUSSION TITLE
Documentation for Postgres may be missing something

### DISCUSSION THREAD

**Discussion by NickStallman** [gramps-project/gramps-web-api#561] [General]
I've tried setting up a new Gramps docker deployment, and wish to use Postgres to better support a rather large database size.
I'm struggling to have it actually use Postgres as the database backend however, and it seems like the documentation might be missing something.

It would be super helpful if there was an example docker file added here to have a known good working setup to start from, rather than following instructions on how to modify it?
https://github.com/gramps-project/gramps-web-docs/tree/main/examples

Also the Postgres page links to https://www.grampsweb.org/multi-tree/ which is a 404.

My specific issue is it's not even trying to use postgres at all, no errors in the logs, no tell tale signs, it just keeps using sqlite.

docker-compose.yml (minimal)
```
services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "80:5000"  # host:docker
    environment:
      GRAMPSWEB_NEW_DB_BACKEND: postgresql
      GRAMPSWEB_TREE: gramps
      GRAMPSWEB_POSTGRES_HOST: postgres_gramps
      GRAMPSWEB_POSTGRES_USER: gramps
      GRAMPSWEB_POSTGRES_PASSWORD: postgres_password_gramps
      GRAMPSWEB_SEARCH_INDEX_DB_URI: postgresql://gramps:postgres_password_gramps@postgres_gramps:5432/gramps
    depends_on:
      - postgres_gramps
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp
  postgres_gramps:
    image: ghcr.io/davidmstraub/gramps-postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres_password_admin
      POSTGRES_PASSWORD_GRAMPS: postgres_password_gramps
      POSTGRES_PASSWORD_GRAMPS_USER: postgres_password_gramps_user
    volumes:
      - postgres_data:/var/lib/postgresql/data
```

Relevant part of the Log:
```
Attaching to gramps-web_grampsweb_1
grampsweb_1           | ls: cannot access '/app/indexdir/*.db': No such file or directory
grampsweb_1           | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
grampsweb_1           | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
grampsweb_1           | [2024-10-26 17:30:23 +0000] [15] [INFO] Starting gunicorn 22.0.0
```
