### ISSUE TITLE
Problem with Deploying Gramps Web with Docker

### ISSUE THREAD

**Issue by charliedaly** [gramps-project/gramps-web-api#519]
I have followed the instructions at https://www.grampsweb.org/Deployment/ and I got the following output:
```
docker-compose up -d
[+] Running 28/20
 ✔ grampsweb_redis 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled             52.8s 
 ✔ grampsweb_celery Pulled                                               101.0s 
 ✔ grampsweb 17 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled        101.0s 
                                                                                 
[+] Running 4/4
 ✔ Network gramps-web-api_default        Created                           0.2s 
 ✔ Container grampsweb_redis             St...                             0.9s 
 ✔ Container grampsweb_celery            S...                              0.1s 
 ✔ Container gramps-web-api-grampsweb-1  Started                           0.0s 
```
So, it all seems to work, when I run docker ps, it shows me that the celery and grampsweb containers are continuously restarting.
```
docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                          PORTS      NAMES
4421af21c61f   ghcr.io/gramps-project/grampsweb:latest   "/docker-entrypoint.…"   16 minutes ago   Restarting (1) 52 seconds ago              grampsweb_celery
87555aa3e0b2   ghcr.io/gramps-project/grampsweb:latest   "/docker-entrypoint.…"   16 minutes ago   Restarting (1) 50 seconds ago              gramps-web-api-grampsweb-1
67c7b7c82200   redis:7.2.4-alpine                        "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes                   6379/tcp   grampsweb_redis
```
There is a lot of log output:
```
docker-compose logs | wc -l
2169
```
It's mostly a repetition of:
```
gramps-web-api-grampsweb-1  | (__main__.py:9): Gtk-CRITICAL **: 12:04:39.173: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
gramps-web-api-grampsweb-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
gramps-web-api-grampsweb-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
gramps-web-api-grampsweb-1  | ERROR [alembic.util.messaging] Requested revision 84960b7d968c overlaps with other requested revisions 66e56620891a
gramps-web-api-grampsweb-1  | FAILED: Requested revision 84960b7d968c overlaps with other requested revisions 66e56620891a
gramps-web-api-grampsweb-1  | Traceback (most recent call last):
gramps-web-api-grampsweb-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
gramps-web-api-grampsweb-1  |   File "<frozen runpy>", line 88, in _run_code
gramps-web-api-grampsweb-1  |   File "/app/src/gramps_webapi/__main__.py", line 234, in <module>
gramps-web-api-grampsweb-1  |     cli(
gramps-web-api-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
gramps-web-api-grampsweb-1  |     return self.main(*args, **kwargs)
gramps-web-api-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-web-api-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
gramps-web-api-grampsweb-1  |     rv = self.invoke(ctx)
gramps-web-api-grampsweb-1  |          ^^^^^^^^^^^^^^^^
gramps-web-api-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
gramps-web-api-grampsweb-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
gramps-web-api-grampsweb-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-web-api-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
gramps-web-api-grampsweb-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
gramps-web-api-grampsweb-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-web-api-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
gramps-web-api-grampsweb-1  |     return ctx.invoke(self.callback, **ctx.params)
gramps-web-api-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-web-api-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
gramps-web-api-grampsweb-1  |     return __callback(*args, **kwargs)
gramps-web-api-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-web-api-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
gramps-web-api-grampsweb-1  |     return f(get_current_context(), *args, **kwargs)
gramps-web-api-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-web-api-grampsweb-1  |   File "/app/src/gramps_webapi/__main__.py", line 118, in migrate_db
gramps-web-api-grampsweb-1  |     subprocess.run(cmd, env=env, check=True)
gramps-web-api-grampsweb-1  |   File "/usr/lib/python3.11/subprocess.py", line 571, in run
gramps-web-api-grampsweb-1  |     raise CalledProcessError(retcode, process.args,
gramps-web-api-grampsweb-1  | subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'alembic', 'upgrade', 'head']' returned non-zero exit status 255.
```
This is all running on `Ubuntu 22.04.4 LTS`.
The YAML file is:
```
version: "3.7"

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "80:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO

  grampsweb_redis:
    image: redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:
```
Docker version:
```
docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.8
 Git commit:        ced0996
 Built:             Sat Oct  7 00:14:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.8
  Git commit:       a61e2b4
  Built:            Sat Oct  7 00:14:30 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
