### ISSUE TITLE
502 Internal server error

### ISSUE THREAD

**Issue by Upp1dy** [gramps-project/gramps-web-api#659]
Hello everyone,

i'm having isues with my Gramps Web instance. Sometimes it gives me the 502 Internal server error if i want to edit something.

My Gramps System Info

Gramps 5.2.4
Gramps Web API 2.8.2
Gramps Web Frontend 25.3.1
Gramps QL 0.3.0
Sifts 1.0.0
locale: en
multi-tree: false
task queue: true
OCR: true
chat: false

This is my docker-compose file

```
services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "80:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GUNICORN_NUM_WORKERS: 2
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2

  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:
```

Here are the logs of the Gramps Web container

> (__main__.py:7): Gtk-CRITICAL **: 13:28:56.386: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> 
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> 
> [2025-06-11 13:28:58 +0000] [11] [INFO] Starting gunicorn 23.0.0
> 
> [2025-06-11 13:28:58 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
> 
> [2025-06-11 13:28:58 +0000] [11] [INFO] Using worker: sync
> 
> [2025-06-11 13:28:58 +0000] [12] [INFO] Booting worker with pid: 12
> 
> [2025-06-11 13:28:58 +0000] [13] [INFO] Booting worker with pid: 13
> 
> (gunicorn:12): Gtk-CRITICAL **: 13:29:02.433: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> (gunicorn:13): Gtk-CRITICAL **: 13:29:02.561: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> ERROR:root:Error parsing list of recent DBs from file /root/.gramps/recent-files-gramps.xml: no element found: line 1, column 0.
> 
> This might indicate a damage to your files.
> 
> If you're sure there is no problem with other files, delete it, and restart Gramps.
> 
> (__main__.py:8): Gtk-CRITICAL **: 13:42:06.000: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> 
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> 
> [2025-06-11 13:42:07 +0000] [12] [INFO] Starting gunicorn 23.0.0
> 
> [2025-06-11 13:42:07 +0000] [12] [INFO] Listening at: http://0.0.0.0:5000 (12)
> 
> [2025-06-11 13:42:07 +0000] [12] [INFO] Using worker: sync
> 
> [2025-06-11 13:42:07 +0000] [13] [INFO] Booting worker with pid: 13
> 
> [2025-06-11 13:42:07 +0000] [14] [INFO] Booting worker with pid: 14
> 
> (gunicorn:13): Gtk-CRITICAL **: 13:42:11.434: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> (gunicorn:14): Gtk-CRITICAL **: 13:42:11.767: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> ERROR:root:Error parsing list of recent DBs from file /root/.gramps/recent-files-gramps.xml: no element found: line 1, column 0.
> 
> This might indicate a damage to your files.
> 
> If you're sure there is no problem with other files, delete it, and restart Gramps.
> 
> [2025-06-11 14:26:07 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:14)
> 
> [2025-06-11 14:26:08 +0000] [12] [ERROR] Worker (pid:14) was sent SIGKILL! Perhaps out of memory?
> 
> [2025-06-11 14:26:08 +0000] [47] [INFO] Booting worker with pid: 47
> 
> (gunicorn:47): Gtk-CRITICAL **: 14:26:10.695: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> [2025-06-11 15:24:09 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:47)
> 
> [2025-06-11 15:24:11 +0000] [12] [ERROR] Worker (pid:47) was sent SIGKILL! Perhaps out of memory?
> 
> [2025-06-11 15:24:11 +0000] [57] [INFO] Booting worker with pid: 57
> 
> (gunicorn:57): Gtk-CRITICAL **: 15:24:13.899: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> 
> [2025-06-11 15:44:46 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:57)
> 
> [2025-06-11 15:44:47 +0000] [12] [ERROR] Worker (pid:57) was sent SIGKILL! Perhaps out of memory?
> 
> [2025-06-11 15:44:47 +0000] [65] [INFO] Booting worker with pid: 65
> 
> (gunicorn:65): Gtk-CRITICAL **: 15:44:49.883: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
